server {
    listen       8080;
    listen  [::]:8080;
    server_name  blog.zibok.org;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Content-Security-Policy "frame-ancestors 'none'; default-src 'self'; img-src 'self' cdn.jsdelivr.net; script-src 'self' 'sha256-NurvQK1R+e55ZOU1SxbmvLvgl8bjZRybNRXp3j1hrMI=' 'sha256-4V8WxmH+ykIlGiV2pbQGmG3szs7GDgKIdFgCddG6ex0=' 'sha256-BRLcjPeCTLE+kBzS2NCS8Q6BLZKMau1zabP5olHaKnE=' cdn.jsdelivr.net dwt.soundclound.com widget.sndcdn.com; style-src 'self' cdn.jsdelivr.net fonts.googleapis.com; font-src 'self' fonts.gstatic.com; frame-src w.soundcloud.com";

    location / {
        root   /var/www/html;
        index  index.html;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

